version: '3'
services:
  web:
    image: praqma/network-multitool
    container_name: web
    command: sleep infinity
    networks:
      - frontend
      - backend
  app:
    image: praqma/network-multitool
    container_name: app
    command: sleep infinity
    networks:
      - backend
  db:
    image: praqma/network-multitool
    container_name: db
    command: sleep infinity
    networks:
      - frontend

networks:
  frontend:
  backend: