version: '3'

services:
  mysqldb:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: database

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
      - 8080:80
      environment:
        PMA_HOST: mysqldb